FROM apache/airflow:3.3.2-python3.12

COPY --chown=airflow:root requirements.txt /tmp/project-requirements.txt
RUN pip install --no-cache-dir -r /tmp/project-requirements.txt

ENV PYTHONPATH=/opt/airflow/project
WORKDIR /opt/airflow/project
